/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;


import JavaClass.Atividades;
import JavaClass.UserSession;
import JavaClass.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Arthur
 */
public class ADM_Users extends javax.swing.JFrame {

    Map<String, Usuario>usuarioMap = new HashMap<>();
    /**
     * Creates new form ADM_Users
     */
    public ADM_Users() {
        initComponents();
        CB_showList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Users = new javax.swing.JComboBox<>();
        LB_SelectUser = new javax.swing.JLabel();
        BT_ExcluirUser = new javax.swing.JButton();
        BT_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        CB_Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_UsersActionPerformed(evt);
            }
        });

        LB_SelectUser.setText("Selecione o usuário:");

        BT_ExcluirUser.setBackground(new java.awt.Color(204, 204, 204));
        BT_ExcluirUser.setForeground(new java.awt.Color(22, 22, 22));
        BT_ExcluirUser.setText("EXCLUIR");
        BT_ExcluirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ExcluirUserActionPerformed(evt);
            }
        });

        BT_Voltar.setText("VOLTAR");
        BT_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LB_SelectUser)
                    .addComponent(CB_Users, 0, 300, Short.MAX_VALUE)
                    .addComponent(BT_ExcluirUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BT_Voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LB_SelectUser)
                .addGap(3, 3, 3)
                .addComponent(CB_Users, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(BT_ExcluirUser)
                .addGap(20, 20, 20)
                .addComponent(BT_Voltar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DAO dao = new DAO();
    
    
    private void CB_showList(){
        List<Usuario> listaUsuarios = dao.listaUsuarios();
        for(Usuario usuario : listaUsuarios){
            CB_Users.addItem(usuario.getEmail());
            usuarioMap.put(usuario.getEmail(),usuario);
        }
    }
    
    private void CB_UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_UsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_UsersActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void BT_ExcluirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ExcluirUserActionPerformed
        String selectedUsuarioEmail = (String) CB_Users.getSelectedItem();
        Usuario selectedUsuario = usuarioMap.get(selectedUsuarioEmail);
        dao.deleteUsuario(selectedUsuario.getEmail());

        CB_Users.removeItem(selectedUsuarioEmail);
    }//GEN-LAST:event_BT_ExcluirUserActionPerformed

    private void BT_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VoltarActionPerformed
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADM_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADM_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADM_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADM_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADM_Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ExcluirUser;
    private javax.swing.JButton BT_Voltar;
    private javax.swing.JComboBox<String> CB_Users;
    private javax.swing.JLabel LB_SelectUser;
    // End of variables declaration//GEN-END:variables
}
