/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import Telas.DAO;
import JavaClass.Usuario;
import JavaClass.Atividades;

/**
 *
 * @author Arthur
 */
public class AtividadesTela extends javax.swing.JFrame {

    /**
     * Creates new form Atividades2
     */
    public AtividadesTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_VoltarAtividades = new java.awt.Button();
        BT_Enviar = new java.awt.Button();
        TX_Atividade = new javax.swing.JTextField();
        LB_Atividade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Descricao = new javax.swing.JTextArea();
        LB_DescricaoACT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BT_VoltarAtividades.setActionCommand("Voltar");
        BT_VoltarAtividades.setLabel("Voltar");
        BT_VoltarAtividades.setPreferredSize(new java.awt.Dimension(50, 30));
        BT_VoltarAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VoltarAtividadesActionPerformed(evt);
            }
        });

        BT_Enviar.setLabel("Enviar");
        BT_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EnviarActionPerformed(evt);
            }
        });

        TX_Atividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_AtividadeActionPerformed(evt);
            }
        });

        LB_Atividade.setText("Digite uma atividade para praticar");

        TA_Descricao.setColumns(20);
        TA_Descricao.setRows(5);
        TA_Descricao.setToolTipText("");
        TA_Descricao.setName(""); // NOI18N
        TA_Descricao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TA_DescricaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TA_Descricao);

        LB_DescricaoACT.setText("Digite uma descrição ou meta para esta atividade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB_DescricaoACT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_Atividade)
                            .addComponent(TX_Atividade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(BT_VoltarAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BT_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_Atividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TX_Atividade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LB_DescricaoACT)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_VoltarAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String[] args) {
        /* Código de inicialização do JFrame */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtividadesTela().setVisible(true);
            }
        });
    }
    private void BT_EnviarActionPerformed(java.awt.event.ActionEvent evt)
    {
        DAO dao = new DAO();
        dao.adicionarAtividade(TX_Atividade.getText(),TA_Descricao.getText());
        JOptionPane.showMessageDialog(null, "Adicionado em 'Minhas Atividades' no menu");
    }

    private void TX_AtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_AtividadeActionPerformed
        
        
    }//GEN-LAST:event_TX_AtividadeActionPerformed

    private void TA_DescricaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TA_DescricaoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TA_DescricaoAncestorAdded

    private void BT_VoltarAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VoltarAtividadesActionPerformed
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_VoltarAtividadesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BT_Enviar;
    private java.awt.Button BT_VoltarAtividades;
    private javax.swing.JLabel LB_Atividade;
    private javax.swing.JLabel LB_DescricaoACT;
    private javax.swing.JTextArea TA_Descricao;
    private javax.swing.JTextField TX_Atividade;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
