/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import JavaClass.UserSession;
import JavaClass.Usuario;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class MeuPerfil extends javax.swing.JFrame {

    /**
     * Creates new form MeuPerfil
     */
    public MeuPerfil() {
        initComponents();
        AutoFill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        BT_Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TX_Nome = new javax.swing.JTextField();
        TX_Email = new javax.swing.JTextField();
        TX_Altura = new javax.swing.JTextField();
        TX_Peso = new javax.swing.JTextField();
        TX_Idade = new javax.swing.JTextField();
        BT_Calculoagua = new javax.swing.JButton();
        BT_CalculoIMC = new javax.swing.JButton();
        BT_Salvar = new javax.swing.JButton();
        LB_Nome = new javax.swing.JLabel();
        LB_Altura = new javax.swing.JLabel();
        LB_Email = new javax.swing.JLabel();
        LB_Peso = new javax.swing.JLabel();
        LB_Idade = new javax.swing.JLabel();
        LB_AguaDia = new javax.swing.JLabel();
        LB_IMC = new javax.swing.JLabel();
        LB_IMCTXT = new javax.swing.JLabel();
        LB_Agua = new javax.swing.JLabel();
        LB_FraseIMC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu perfil");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));

        BT_Sair.setBackground(new java.awt.Color(102, 153, 255));
        BT_Sair.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        BT_Sair.setForeground(new java.awt.Color(255, 255, 255));
        BT_Sair.setText("SAIR");
        BT_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BT_Sair)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BT_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("  MEU PERFIL");

        TX_Nome.setBackground(new java.awt.Color(204, 204, 204));
        TX_Nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TX_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_NomeActionPerformed(evt);
            }
        });

        TX_Email.setBackground(new java.awt.Color(204, 204, 204));
        TX_Email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TX_Altura.setBackground(new java.awt.Color(204, 204, 204));
        TX_Altura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TX_Altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_AlturaActionPerformed(evt);
            }
        });

        TX_Peso.setBackground(new java.awt.Color(204, 204, 204));
        TX_Peso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TX_Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TX_PesoActionPerformed(evt);
            }
        });

        TX_Idade.setBackground(new java.awt.Color(204, 204, 204));
        TX_Idade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        BT_Calculoagua.setBackground(new java.awt.Color(102, 153, 255));
        BT_Calculoagua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BT_Calculoagua.setForeground(new java.awt.Color(255, 255, 255));
        BT_Calculoagua.setText("CALCULAR LITROS DIARIO");
        BT_Calculoagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CalculoaguaActionPerformed(evt);
            }
        });

        BT_CalculoIMC.setBackground(new java.awt.Color(102, 153, 255));
        BT_CalculoIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BT_CalculoIMC.setForeground(new java.awt.Color(255, 255, 255));
        BT_CalculoIMC.setText("CALCULO IMC");
        BT_CalculoIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CalculoIMCActionPerformed(evt);
            }
        });

        BT_Salvar.setBackground(new java.awt.Color(102, 153, 255));
        BT_Salvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BT_Salvar.setForeground(new java.awt.Color(255, 255, 255));
        BT_Salvar.setText("SALVAR");
        BT_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_SalvarActionPerformed(evt);
            }
        });

        LB_Nome.setText("Nome");

        LB_Altura.setText("Altura");

        LB_Email.setText("Email");

        LB_Peso.setText("Peso");

        LB_Idade.setText("Idade");

        LB_AguaDia.setText("Consumo de água recomendado por dia");

        LB_IMC.setText("Seu IMC é:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BT_Calculoagua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(BT_CalculoIMC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(BT_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LB_IMC)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LB_IMCTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB_FraseIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LB_AguaDia)
                            .addComponent(LB_Email)
                            .addComponent(LB_Nome)
                            .addComponent(TX_Nome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LB_Altura)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TX_Altura))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_Peso)
                                    .addComponent(TX_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_Idade)
                                    .addComponent(TX_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TX_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(LB_Agua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Nome)
                .addGap(1, 1, 1)
                .addComponent(TX_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Email)
                .addGap(4, 4, 4)
                .addComponent(TX_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB_Altura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TX_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB_Idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TX_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LB_AguaDia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB_Peso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TX_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Agua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(LB_IMC)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LB_FraseIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_IMCTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT_Calculoagua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_CalculoIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DAO dao = new DAO();
    Usuario usuario = null;
    private void AutoFill()
    {
        usuario = dao.buscaInfoUsuario(UserSession.getInstance().email());
        TX_Nome.setText(usuario.getNome());
        TX_Email.setText(usuario.getEmail());
        TX_Altura.setText(usuario.getAltura());
        TX_Idade.setText(usuario.getIdade());
        TX_Peso.setText(usuario.getPeso());
    }
    
    private void TX_AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_AlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TX_AlturaActionPerformed

    private void TX_PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TX_PesoActionPerformed

    private void BT_CalculoaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CalculoaguaActionPerformed
        String pesoTXT = TX_Peso.getText();
        
        double pesoNum = Double.parseDouble(pesoTXT.replace(',', '.'));
        double litros = pesoNum * 0.035;
           
        String litrosFormat = String.format("%.2f",litros);
        LB_Agua.setText(litrosFormat);
      
        JOptionPane.showMessageDialog(null, "A quantide de litros diario que deve ingerir é de: " + litrosFormat);
    }//GEN-LAST:event_BT_CalculoaguaActionPerformed

    private void BT_CalculoIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CalculoIMCActionPerformed
        String pesoTXT = TX_Peso.getText();
        String alturaTXT = TX_Altura.getText();
        
        double pesoNum = Double.parseDouble(pesoTXT.replace(',', '.'));
        double alturaNum = Double.parseDouble(alturaTXT.replace(',', '.'));
        
        double IMC = pesoNum/(alturaNum*alturaNum);
        String IMCFormatado = String.format("%.2f",IMC);
        LB_IMCTXT.setText(IMCFormatado);

        if(IMC <18.5){
            LB_FraseIMC.setText("Peso inferior ao normal");
        }else if (IMC >=18.5 && IMC <= 24.9){
            LB_FraseIMC.setText("Peso normal");
        }else if (IMC >=25.0 && IMC <= 30){
            LB_FraseIMC.setText("Peso superior ao normal");
        }else{
            LB_FraseIMC.setText("Peso a cima do normal");
        }
    }//GEN-LAST:event_BT_CalculoIMCActionPerformed

    private void BT_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SairActionPerformed
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_SairActionPerformed

    private void TX_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TX_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TX_NomeActionPerformed

    private void BT_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_SalvarActionPerformed
        String peso = TX_Peso.getText();
        String altura = TX_Altura.getText();
        String idade = TX_Idade.getText();
        usuario.setAltura(altura);
        usuario.setPeso(peso);
        usuario.setIdade(idade);
        
        dao.editProfile(usuario);  
    }//GEN-LAST:event_BT_SalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CalculoIMC;
    private javax.swing.JButton BT_Calculoagua;
    private javax.swing.JButton BT_Sair;
    private javax.swing.JButton BT_Salvar;
    private javax.swing.JLabel LB_Agua;
    private javax.swing.JLabel LB_AguaDia;
    private javax.swing.JLabel LB_Altura;
    private javax.swing.JLabel LB_Email;
    private javax.swing.JLabel LB_FraseIMC;
    private javax.swing.JLabel LB_IMC;
    private javax.swing.JLabel LB_IMCTXT;
    private javax.swing.JLabel LB_Idade;
    private javax.swing.JLabel LB_Nome;
    private javax.swing.JLabel LB_Peso;
    private javax.swing.JTextField TX_Altura;
    private javax.swing.JTextField TX_Email;
    private javax.swing.JTextField TX_Idade;
    private javax.swing.JTextField TX_Nome;
    private javax.swing.JTextField TX_Peso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
