/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import JavaClass.Atividades;
import JavaClass.UserSession;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author Arthur
 */
public class MinhasAtividades extends javax.swing.JFrame {

    Map<String, Atividades>atividadesMap = new HashMap<>();
    
    /**
     * Creates new form MinhasAtividades
     */
    public MinhasAtividades() {
        initComponents();
        CB_showList();
        CB_Listener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_MinhasATV = new javax.swing.JComboBox<>();
        LB_DescricaoACT = new javax.swing.JLabel();
        LB_Atividade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Descricao = new javax.swing.JTextArea();
        BT_Voltar = new javax.swing.JButton();
        BT_Editar = new java.awt.Button();
        BT_Deletar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minhas atividades");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        CB_MinhasATV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_MinhasATVActionPerformed(evt);
            }
        });

        LB_DescricaoACT.setText("Descrição da atividade:");

        LB_Atividade.setText("Selecione uma atividade");

        TA_Descricao.setColumns(20);
        TA_Descricao.setRows(5);
        TA_Descricao.setToolTipText("");
        TA_Descricao.setName(""); // NOI18N
        TA_Descricao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TA_DescricaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TA_Descricao);

        BT_Voltar.setBackground(new java.awt.Color(240, 240, 240));
        BT_Voltar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BT_Voltar.setForeground(new java.awt.Color(22, 22, 22));
        BT_Voltar.setText("Voltar");
        BT_Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VoltarActionPerformed(evt);
            }
        });

        BT_Editar.setBackground(new java.awt.Color(240, 240, 240));
        BT_Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Editar.setForeground(new java.awt.Color(22, 22, 22));
        BT_Editar.setLabel("Editar");
        BT_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EditarActionPerformed(evt);
            }
        });

        BT_Deletar.setBackground(new java.awt.Color(240, 240, 240));
        BT_Deletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_Deletar.setForeground(new java.awt.Color(22, 22, 22));
        BT_Deletar.setLabel("Deletar");
        BT_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_DeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_DescricaoACT, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BT_Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(CB_MinhasATV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LB_Atividade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BT_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LB_Atividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_MinhasATV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(LB_DescricaoACT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(BT_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DAO dao = new DAO();
    
    private void CB_MinhasATVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_MinhasATVActionPerformed
        
    }//GEN-LAST:event_CB_MinhasATVActionPerformed
    
    private void CB_showList(){
        List<Atividades> listaAtividades = dao.listarAtividade(UserSession.getInstance().email());
        for(Atividades atividade : listaAtividades){
            CB_MinhasATV.addItem(atividade.getAtividade());
            atividadesMap.put(atividade.getAtividade(),atividade);
        }
    }
    
    private void CB_Listener()
    {
        CB_MinhasATV.addItemListener(new ItemListener() 
        {
            public void itemStateChanged(ItemEvent e)
            {
                if(e.getStateChange()== ItemEvent.SELECTED){
                    String atividadeNome = (String) e.getItem();
                    Atividades atividadeSelecionada = atividadesMap.get(atividadeNome);
                    TA_Descricao.setText(atividadeSelecionada.getDescricao());
                   
                }
            }
        });
        String primeiroItem = (String) CB_MinhasATV.getSelectedItem();
        
        if (primeiroItem != null){
            Atividades primeiraAtividade = atividadesMap.get(primeiroItem);
            TA_Descricao.setText(primeiraAtividade.getDescricao());
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem atividades, crie uma na página de 'Adiconar atividades'.");
        }
        
    }
    
    private void TA_DescricaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TA_DescricaoAncestorAdded
        
    }//GEN-LAST:event_TA_DescricaoAncestorAdded

    private void BT_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VoltarActionPerformed
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_VoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void BT_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_DeletarActionPerformed
        
        String selectedActivityName = (String) CB_MinhasATV.getSelectedItem();
        Atividades selectedActivity = atividadesMap.get(selectedActivityName);
        dao.deleteAtividade(selectedActivity.getId());

        CB_MinhasATV.removeItem(selectedActivityName);
        
    }//GEN-LAST:event_BT_DeletarActionPerformed

    private void BT_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EditarActionPerformed
        String selectedActivityName = (String) CB_MinhasATV.getSelectedItem();
        Atividades selectedActivity = atividadesMap.get(selectedActivityName);
        dao.editAtividade(TA_Descricao.getText(),selectedActivity.getId());
    }//GEN-LAST:event_BT_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhasAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhasAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhasAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhasAtividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhasAtividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BT_Deletar;
    private java.awt.Button BT_Editar;
    private javax.swing.JButton BT_Voltar;
    private javax.swing.JComboBox<String> CB_MinhasATV;
    private javax.swing.JLabel LB_Atividade;
    private javax.swing.JLabel LB_DescricaoACT;
    private javax.swing.JTextArea TA_Descricao;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
